/**
 * 📊 Financial Reports Generator
 * محرك توليد التقارير المالية - يدعم PDF, Excel, Word
 */

import jsPDF from 'jspdf';
import * as XLSX from 'xlsx';
import JSZip from 'jszip';
import { saveAs } from 'file-saver';

// ==================== Types ====================

export interface ReportData {
    title: string;
    period: string;
    generatedAt: string;
    generatedBy: string;
    
    // Financial Summary
    totalRevenue: number;
    totalExpenses: number;
    netProfit: number;
    profitMargin: number;
    
    // Details
    bookings: BookingReportItem[];
    expenses: ExpenseReportItem[];
    payments: PaymentReportItem[];
    
    // Charts data
    revenueByMonth?: { month: string; amount: number }[];
    expensesByCategory?: { category: string; amount: number }[];
}

export interface BookingReportItem {
    id: string;
    date: string;
    unitName: string;
    customerName: string;
    totalAmount: number;
    amountPaid: number;
    remainingAmount: number;
    status: string;
}

export interface ExpenseReportItem {
    id: string;
    date: string;
    category: string;
    description: string;
    amount: number;
    status: string;
}

export interface PaymentReportItem {
    id: string;
    date: string;
    bookingId: string;
    amount: number;
    type: string;
}

// ==================== Helpers ====================

const formatCurrency = (amount: number): string => {
    return new Intl.NumberFormat('ar-SA', {
        style: 'currency',
        currency: 'SAR',
        minimumFractionDigits: 2
    }).format(amount);
};

const formatDate = (date: string): string => {
    return new Date(date).toLocaleDateString('ar-SA', {
        year: 'numeric',
        month: 'long',
        day: 'numeric'
    });
};

// ==================== PDF Export ====================

/**
 * توليد تقرير PDF
 */
export const generatePDFReport = (data: ReportData): void => {
    const doc = new jsPDF('p', 'mm', 'a4');
    
    // Configure font for Arabic (if available)
    doc.setFont('helvetica');
    
    let y = 20;
    
    // Header
    doc.setFontSize(18);
    doc.text(data.title, 105, y, { align: 'center' });
    y += 10;
    
    doc.setFontSize(10);
    doc.text(`${data.period}`, 105, y, { align: 'center' });
    y += 6;
    doc.text(`${formatDate(data.generatedAt)}`, 105, y, { align: 'center' });
    y += 15;
    
    // Financial Summary
    doc.setFontSize(14);
    doc.text('Financial Summary', 20, y);
    y += 8;
    
    doc.setFontSize(10);
    doc.text(`Total Revenue: ${formatCurrency(data.totalRevenue)}`, 25, y);
    y += 6;
    doc.text(`Total Expenses: ${formatCurrency(data.totalExpenses)}`, 25, y);
    y += 6;
    doc.text(`Net Profit: ${formatCurrency(data.netProfit)}`, 25, y);
    y += 6;
    doc.text(`Profit Margin: ${data.profitMargin.toFixed(2)}%`, 25, y);
    y += 15;
    
    // Bookings Summary
    if (data.bookings.length > 0) {
        doc.setFontSize(12);
        doc.text('Bookings', 20, y);
        y += 8;
        
        doc.setFontSize(9);
        doc.text('Date', 25, y);
        doc.text('Unit', 60, y);
        doc.text('Customer', 95, y);
        doc.text('Amount', 130, y);
        doc.text('Paid', 160, y);
        y += 5;
        
        data.bookings.slice(0, 10).forEach(booking => {
            if (y > 270) {
                doc.addPage();
                y = 20;
            }
            doc.text(booking.date, 25, y);
            doc.text(booking.unitName.substring(0, 20), 60, y);
            doc.text(booking.customerName.substring(0, 20), 95, y);
            doc.text(formatCurrency(booking.totalAmount), 130, y);
            doc.text(formatCurrency(booking.amountPaid), 160, y);
            y += 6;
        });
        
        if (data.bookings.length > 10) {
            y += 2;
            doc.text(`... and ${data.bookings.length - 10} more bookings`, 25, y);
        }
        y += 10;
    }
    
    // Save
    doc.save(`${data.title}_${data.period}.pdf`);
};

// ==================== Excel Export ====================

/**
 * توليد تقرير Excel
 */
export const generateExcelReport = (data: ReportData): void => {
    const wb = XLSX.utils.book_new();
    
    // Summary Sheet
    const summaryData = [
        ['Financial Report', ''],
        ['Period', data.period],
        ['Generated At', data.generatedAt],
        ['Generated By', data.generatedBy],
        [''],
        ['Financial Summary', ''],
        ['Total Revenue', data.totalRevenue],
        ['Total Expenses', data.totalExpenses],
        ['Net Profit', data.netProfit],
        ['Profit Margin', `${data.profitMargin.toFixed(2)}%`],
    ];
    const wsSummary = XLSX.utils.aoa_to_sheet(summaryData);
    XLSX.utils.book_append_sheet(wb, wsSummary, 'Summary');
    
    // Bookings Sheet
    if (data.bookings.length > 0) {
        const bookingsData = [
            ['ID', 'Date', 'Unit', 'Customer', 'Total Amount', 'Amount Paid', 'Remaining', 'Status']
        ];
        data.bookings.forEach(b => {
            bookingsData.push([
                b.id,
                b.date,
                b.unitName,
                b.customerName,
                b.totalAmount,
                b.amountPaid,
                b.remainingAmount,
                b.status
            ]);
        });
        const wsBookings = XLSX.utils.aoa_to_sheet(bookingsData);
        XLSX.utils.book_append_sheet(wb, wsBookings, 'Bookings');
    }
    
    // Expenses Sheet
    if (data.expenses.length > 0) {
        const expensesData = [
            ['ID', 'Date', 'Category', 'Description', 'Amount', 'Status']
        ];
        data.expenses.forEach(e => {
            expensesData.push([
                e.id,
                e.date,
                e.category,
                e.description,
                e.amount,
                e.status
            ]);
        });
        const wsExpenses = XLSX.utils.aoa_to_sheet(expensesData);
        XLSX.utils.book_append_sheet(wb, wsExpenses, 'Expenses');
    }
    
    // Payments Sheet
    if (data.payments.length > 0) {
        const paymentsData = [
            ['ID', 'Date', 'Booking ID', 'Amount', 'Type']
        ];
        data.payments.forEach(p => {
            paymentsData.push([
                p.id,
                p.date,
                p.bookingId,
                p.amount,
                p.type
            ]);
        });
        const wsPayments = XLSX.utils.aoa_to_sheet(paymentsData);
        XLSX.utils.book_append_sheet(wb, wsPayments, 'Payments');
    }
    
    // Charts Data
    if (data.revenueByMonth && data.revenueByMonth.length > 0) {
        const chartData = [['Month', 'Revenue']];
        data.revenueByMonth.forEach(item => {
            chartData.push([item.month, item.amount]);
        });
        const wsChart = XLSX.utils.aoa_to_sheet(chartData);
        XLSX.utils.book_append_sheet(wb, wsChart, 'Revenue Chart Data');
    }
    
    // Save
    XLSX.writeFile(wb, `${data.title}_${data.period}.xlsx`);
};

// ==================== Word Export (as HTML in ZIP) ====================

/**
 * توليد تقرير Word (HTML format)
 */
export const generateWordReport = async (data: ReportData): Promise<void> => {
    const htmlContent = `
<!DOCTYPE html>
<html dir="rtl" lang="ar">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${data.title}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            direction: rtl;
            padding: 40px;
            line-height: 1.6;
        }
        h1 { color: #1e3a8a; text-align: center; }
        h2 { color: #3b82f6; border-bottom: 2px solid #3b82f6; padding-bottom: 5px; }
        .summary { background: #f0f9ff; padding: 20px; border-radius: 8px; margin: 20px 0; }
        .summary-item { margin: 10px 0; font-size: 16px; }
        .summary-item strong { display: inline-block; width: 150px; }
        table { width: 100%; border-collapse: collapse; margin: 20px 0; }
        th, td { border: 1px solid #ddd; padding: 10px; text-align: right; }
        th { background: #3b82f6; color: white; }
        tr:nth-child(even) { background: #f9fafb; }
        .positive { color: #10b981; font-weight: bold; }
        .negative { color: #ef4444; font-weight: bold; }
    </style>
</head>
<body>
    <h1>${data.title}</h1>
    <p style="text-align: center; color: #64748b;">
        ${data.period}<br>
        تم الإنشاء في: ${formatDate(data.generatedAt)}<br>
        بواسطة: ${data.generatedBy}
    </p>
    
    <div class="summary">
        <h2>الملخص المالي</h2>
        <div class="summary-item"><strong>إجمالي الإيرادات:</strong> ${formatCurrency(data.totalRevenue)}</div>
        <div class="summary-item"><strong>إجمالي المصروفات:</strong> ${formatCurrency(data.totalExpenses)}</div>
        <div class="summary-item"><strong>صافي الربح:</strong> <span class="${data.netProfit >= 0 ? 'positive' : 'negative'}">${formatCurrency(data.netProfit)}</span></div>
        <div class="summary-item"><strong>هامش الربح:</strong> ${data.profitMargin.toFixed(2)}%</div>
    </div>
    
    ${data.bookings.length > 0 ? `
    <h2>الحجوزات</h2>
    <table>
        <thead>
            <tr>
                <th>التاريخ</th>
                <th>الوحدة</th>
                <th>العميل</th>
                <th>المبلغ الإجمالي</th>
                <th>المبلغ المدفوع</th>
                <th>المتبقي</th>
                <th>الحالة</th>
            </tr>
        </thead>
        <tbody>
            ${data.bookings.map(b => `
                <tr>
                    <td>${b.date}</td>
                    <td>${b.unitName}</td>
                    <td>${b.customerName}</td>
                    <td>${formatCurrency(b.totalAmount)}</td>
                    <td>${formatCurrency(b.amountPaid)}</td>
                    <td>${formatCurrency(b.remainingAmount)}</td>
                    <td>${b.status}</td>
                </tr>
            `).join('')}
        </tbody>
    </table>
    ` : ''}
    
    ${data.expenses.length > 0 ? `
    <h2>المصروفات</h2>
    <table>
        <thead>
            <tr>
                <th>التاريخ</th>
                <th>الفئة</th>
                <th>الوصف</th>
                <th>المبلغ</th>
                <th>الحالة</th>
            </tr>
        </thead>
        <tbody>
            ${data.expenses.map(e => `
                <tr>
                    <td>${e.date}</td>
                    <td>${e.category}</td>
                    <td>${e.description}</td>
                    <td>${formatCurrency(e.amount)}</td>
                    <td>${e.status}</td>
                </tr>
            `).join('')}
        </tbody>
    </table>
    ` : ''}
    
    <hr style="margin: 40px 0; border: none; border-top: 2px solid #e5e7eb;">
    <p style="text-align: center; color: #9ca3af; font-size: 12px;">
        تم إنشاء هذا التقرير تلقائياً من نظام إدارة المشاريع
    </p>
</body>
</html>
    `;
    
    // Create ZIP with HTML file
    const zip = new JSZip();
    zip.file(`${data.title}.html`, htmlContent);
    
    const content = await zip.generateAsync({ type: 'blob' });
    saveAs(content, `${data.title}_${data.period}.zip`);
};

// ==================== Print Report ====================

/**
 * طباعة التقرير
 */
export const printReport = (reportHtml: string): void => {
    const printWindow = window.open('', '_blank');
    if (printWindow) {
        printWindow.document.write(`
            <!DOCTYPE html>
            <html dir="rtl" lang="ar">
            <head>
                <meta charset="UTF-8">
                <title>طباعة التقرير</title>
                <style>
                    body { font-family: Arial, sans-serif; direction: rtl; padding: 20px; }
                    @media print {
                        body { padding: 0; }
                        .no-print { display: none; }
                    }
                </style>
            </head>
            <body>
                ${reportHtml}
                <script>
                    window.onload = function() {
                        window.print();
                        window.onafterprint = function() { window.close(); }
                    }
                </script>
            </body>
            </html>
        `);
        printWindow.document.close();
    }
};

// ==================== Quick Summary ====================

/**
 * توليد ملخص سريع للعرض
 */
export const generateQuickSummary = (data: ReportData): string => {
    return `
📊 ${data.title}
📅 ${data.period}

💰 إجمالي الإيرادات: ${formatCurrency(data.totalRevenue)}
💸 إجمالي المصروفات: ${formatCurrency(data.totalExpenses)}
📈 صافي الربح: ${formatCurrency(data.netProfit)}
📊 هامش الربح: ${data.profitMargin.toFixed(2)}%

📦 الحجوزات: ${data.bookings.length}
💳 الدفعات: ${data.payments.length}
🧾 المصروفات: ${data.expenses.length}
    `.trim();
};
